### 회원가입
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "email": "example2@example.com",
  "password": "Ex@mp1e!!",
  "passwordConfirm": "Ex@mp1e!!",
  "nickname": "예매자2"
}